name: Organization Invitation
description: Request to join this organization. The bot will send an invite after submission.
title: "Please invite me to the organization"
labels: [github-invitation]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest! After you submit this issue, a bot will send an invitation to the specified GitHub account.
        If you want to use a different account than the issue author, please provide the username below.
  - type: input
    id: username
    attributes:
      label: Your GitHub username (optional)
      description: Leave empty to invite the issue author
      placeholder: e.g. your-username
    validations:
      required: false
  - type: textarea
    id: intro
    attributes:
      label: Short introduction or motivation (optional)
      placeholder: Tell us a bit about yourself or what you’d like to work on.
  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      options:
        - label: I have read and agree to abide by the organization’s Code of Conduct
          required: true
